#!/bin/bash
name=$(jq -r ".name" data.json | sed 's/.*/\u&/')
weight=$(jq '.weight / 10' data.json | awk '{printf "%.0f", $1}')
height=$(jq '.height / 10' data.json | awk '{printf "%.1f", $1}')
type=$(jq -r ".types[].type.name" data.json | sed 's/.*/\u&/')

echo “$name is of type $type, weighs $weight\kg, and is $height\m tall.”
