#!/bin/bash
output_file="pokemon_summary.csv"
mkdir -p pokemon_data

echo "Name, Height (m), Weight (kg)" > "$output_file"
for file in pokemon_data/*;do
	name=$(jq -r ".name" "${file}" | sed 's/.*/\u&/')
	formatted_weight=$(jq '.weight / 10' "${file}" | awk '{printf "%.0f", $1}')
	formatted_height=$(jq '.height / 10' "${file}" | awk '{printf "%.1f", $1}')
	
	echo "${name}, ${formatted_height}, ${formatted_weight}" >> "$output_file"
done
awk -F',' '
NR > 1 {
	total_weight += $3;
	total_height += $2;
	count++
}
END {
	if (count > 0) {
		printf "Average Weight(kg): %.2f\nAverage Height(m): %.2f\n", total_weight/count, total_height/count
	} else {
		print "No data found."
	}
}
' "$output_file"
